version: '3'
services:
  app:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      POSTGRES_DB: bookDB
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: bookDB
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5111:5432"
