version: "3"

services:
  db:
    restart: always
    image: postgres:15
    ports:
      - "5123:5432"
    environment:
      - POSTGRES_USER=su
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=bookDB
    volumes:
      - "postgres:/var/lib/postgresql/data"
    networks:
      - book_net

  web:
    restart: always
    build:
      context: .
    env_file:
      - .env.master
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - book_net


volumes:
  postgres: {}

networks:
  book_net:
    external: true