"""user_manager

Revision ID: 130cabb914e9
Revises: 999ebbc4fc3f
Create Date: 2023-11-27 14:20:32.227170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '130cabb914e9'
down_revision = '999ebbc4fc3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_manager', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_manager')
    # ### end Alembic commands ###
