"""Appointment Start time

Revision ID: d5cf03ee8db6
Revises: fc3adc935acf
Create Date: 2023-11-29 08:11:55.447353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5cf03ee8db6'
down_revision = 'fc3adc935acf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('start_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'start_time')
    # ### end Alembic commands ###
