"""Appointment User ID

Revision ID: f259365c1863
Revises: d5cf03ee8db6
Create Date: 2023-11-29 08:49:00.884157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f259365c1863'
down_revision = 'd5cf03ee8db6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'appointments', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'user_id')
    # ### end Alembic commands ###
